stickers/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.contrib import admin

from stickers import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.IndexView.as_view(), name = 'index'),
    #url(r'^desktop/', include('tasks.urls', namespace = "tasks")),
    url(r'^accounts/', include('registration.urls')),
    url(r'^accounts/profile/', include('tasks.urls', namespace = "tasks")),
    url(r'', include('social_auth.urls')),
]

tasks/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from tasks import views

urlpatterns = [
    url(r'^$', views.TaskListView.as_view(), name = 'tasks-list'),
    url(r'^(?P<pk>\d+)$', views.TaskDetailView.as_view(), name = 'task-detail'),
    url(r'^newtask/$', views.TaskCreateView.as_view(), name = 'create-task'),
    url(r'^deletetask/(?P<pk>\d+)$', views.TaskDeleteView.as_view(), name = 'delete-task'),
    url(r'^edittask/(?P<pk>\d+)$', views.TaskUpdateView.as_view(), name = 'edit-task'),
    url(r'^(?P<pk>\d+)/newitem/$', views.TaskItemCreateView.as_view(), name = 'create-item'),
    url(r'^edititem/(?P<pk>\d+)$', views.TaskItemUpdateView.as_view(), name = 'edit-item'),
    url(r'^deleteitem/(?P<pk>\d+)$', views.TaskItemDeleteView.as_view(), name = 'delete-item'),
    #url(r'^(?P<pk>\d+)/$', views.CourseDetailView.as_view(), name = 'course'),
    #Урлы для редактирование курса
    #url(r'^add/$', views.CourseCreateView.as_view(), name = 'create-course'),
    #url(r'^edit/(?P<pk>\d+)/$', views.CourseUpdateView.as_view(), name = 'edit-course'),
    #url(r'^remove/(?P<pk>\d+)/$', views.CourseDeleteView.as_view(), name = 'remove-course'),
    #Урлы для редактирования урока
#    url(r'^(?P<pk>\d+)/add_lesson/$', views.create_lesson, name = 'create-lesson'),
#    url(r'^(?P<pk>\d+)/edit_lesson/$', views.edit_lesson, name = 'edit-lesson'),
#    url(r'^(?P<pk>\d+)/remove_lesson/$', views.remove_lesson, name = 'remove-lesson'),
]

tasks/models.py
#-*- coding: utf-8 -*-
import datetime

from datetime import date
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User


class Task (models.Model):
    title = models.CharField(verbose_name=u'Заголовок', max_length=35, blank=True)
    theme = models.CharField(verbose_name=u'Тема', max_length=10, choices=((u'работа', u'работа'), (u'личное', u'личное'),
                            (u'семья', u'семья'), (u'покупки', u'покупки'), (u'разное', u'разное')), )
    color = models.CharField(verbose_name=u'Цвет', max_length=10, choices=(('red', u'красный'), ('yellow', u'желтый'),
                            ('blue', u'голубой'), ('grey', u'серый'), (u'viollent', u'фиолетовый')), )
    user = models.ForeignKey(User, verbose_name=u'Пользователь', null=True, editable=True)
    impotent = models.BooleanField(verbose_name=u'Важное')
    time_public = models.DateTimeField(verbose_name=u'Время создания', editable=True, auto_now_add=True)
    time_finish = models.DateField(blank=True, null=True, verbose_name=u'Срок выполнения', help_text='например, 09.07.2015')


    #Define stickers, which not done
    def not_done(self):
        self.done_status = 'not items'
        if len(self.taskitem_set.all()) != 0:
            if len(self.taskitem_set.all()) == len(self.taskitem_set.all().filter(status=True)):
                self.done_status = 'all done'
            else:
                self.done_status = 'undone'
        return self.done_status


    #fire stikers
    def fire(self):
        if self.time_finish is not None:
            if self.time_finish <= date.today() and self.not_done() is 'undone':
                return True
            else:
                return False
        return False

    def __unicode__(self):
        return self.title

class TaskItem (models.Model):
    discription = models.CharField(verbose_name=u'Что не забыть?', max_length=50)
    status = models.BooleanField(verbose_name=u'Сделано!')
    commontask = models.ForeignKey(Task, verbose_name=u'Задача')

    class Meta:
        ordering = ['status']

    def __unicode__(self):
        return self.discription

tasks/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib import auth
from django.core.urlresolvers import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from tasks.models import Task, TaskItem


class MixinUserContext(object):
    def get_context_data(self, **kwargs):
        context = super(MixinUserContext, self).get_context_data(**kwargs)
        context['username'] = auth.get_user(self.request).username
        return context

# Create task list
class TaskListView(MixinUserContext, ListView):
    model = Task
    #paginate_by = 8
    def get_context_data(self, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)
        #context['username'] = auth.get_user(self.request).username
        tasks = Task.objects.order_by('time_finish').filter(theme__in = ['семья', 'разное']).filter(impotent = True)
        self.paramets = dict(self.request.GET)
        self.urgent = '-time_public'
        self.theme = ['работа', 'личное', 'семья', 'покупки', 'разное']

        if len(self.request.GET):
            if self.paramets.has_key('Urgent'):
                self.urgent = 'time_finish'
            if self.paramets.has_key('theme'):
                if int(self.paramets['theme'][0]) is not 5:
                    self.theme = [self.theme[int(self.paramets['theme'][0])]]
            if self.paramets.has_key('Impotent'):

                tasks = Task.objects.order_by(self.urgent).filter(theme__in = self.theme).filter(impotent = True)
                context['tasks'] = tasks
                print self.urgent, self.theme
                return context
        print self.urgent, self.theme
        tasks = Task.objects.order_by(self.urgent).filter(theme__in = self.theme)
        context['tasks'] = tasks

        return context


#Create detail info about task
class TaskDetailView(MixinUserContext, DetailView):
    model = Task

    def get_context_data(self, **kwargs):
        context = super(TaskDetailView, self).get_context_data(**kwargs)
        task = get_object_or_404(Task, pk = self.kwargs['pk'])
        context['task'] = task
        #context['username'] = auth.get_user(self.request).username
        return context

#Create new sticker
class TaskCreateView(MixinUserContext, CreateView):
    model = Task
    success_url = reverse_lazy('tasks:tasks-list')
    fields = ['title', 'theme', 'color', 'user' ,'impotent', 'time_finish']
  


    def get_form(self, form_class):
        form = super(TaskCreateView, self).get_form(form_class)
        form.fields['time_finish'].widget.attrs.update({'class': 'datepicker'})
        form.fields['user']
        return form

    def get_initial(self):
        context = {}
        context['theme'] = u'разное'
        context['color'] = 'yellow'

        context['user'] = auth.get_user(self.request).id
        return context

    def get_context_data(self, **kwargs):
        context = super(TaskCreateView, self).get_context_data(**kwargs)
        context['page_title'] = u"Создать напоминалку"
        #context['username'] = auth.get_user(self.request).username
        print type(auth.get_user(self.request).id)
        return context

    def form_valid(self, form):
        self.application = form.save()
        messages.success(self.request, u'Напоминалка {} созданна. Добавь сколько хочешь задач на нее!'.format(self.application.title))
        return super(TaskCreateView, self).form_valid(form)


#Delete current sticker
class TaskDeleteView(MixinUserContext, DeleteView):
    model = Task
    success_url = reverse_lazy('tasks:tasks-list')

    def delete(self, request, *args, **kwargs):
        task = super (TaskDeleteView, self).delete(request, *args, **kwargs)
        messages.success(self.request, u'Напоминалка {} удалена'.format(self.object.title))
        return task


#Update current sticker
class TaskUpdateView(MixinUserContext, UpdateView):
    model = Task
    fields = ['title', 'theme', 'color', 'impotent', 'time_finish']

    def get_success_url(self):
        return reverse_lazy('tasks:task-detail', kwargs={'pk':self.kwargs['pk']})

    def form_valid(self, form):
        self.application = form.save()
        messages.success(self.request, u'Напоминалка {} изменены'.format(self.application.title))
        return super(TaskUpdateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(TaskUpdateView, self).get_context_data(**kwargs)
        context['page_title'] = u"Редактирование напоминалки"
        #context['username'] = auth.get_user(self.request).username
        return context


#Create item of task
class TaskItemCreateView(MixinUserContext, CreateView):
    model = TaskItem
    #success_url = reverse_lazy('tasks:tasks-list')
    fields = ['discription', 'status', 'commontask']

    def get_initial(self):
        print self.kwargs['pk']
        return {'commontask': self.kwargs['pk'],}

    def get_success_url(self):
        return reverse_lazy('tasks:task-detail', kwargs={'pk':self.kwargs['pk']})

    def get_context_data(self, **kwargs):
        context = super(TaskItemCreateView, self).get_context_data(**kwargs)
        context['page_title'] = u"Создать задачу"
        #context['username'] = auth.get_user(self.request).username
        return context

    def form_valid(self, form):
        self.application = form.save()
        messages.success(self.request, u'Задача создана')
        return super(TaskItemCreateView, self).form_valid(form)


#Update current task
class TaskItemUpdateView(MixinUserContext, UpdateView):
    model = TaskItem
    #success_url = reverse_lazy('tasks:tasks-list')
    fields = ['discription', 'status', 'commontask']


    def get_success_url(self):
        taskitem = get_object_or_404(TaskItem, id = self.kwargs['pk'])
        return reverse_lazy('tasks:task-detail', kwargs={'pk':taskitem.commontask.id})

    def form_valid(self, form):
        self.application = form.save()
        messages.success(self.request, u'Задача изменена')
        return super(TaskItemUpdateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(TaskItemUpdateView, self).get_context_data(**kwargs)
        context['page_title'] = u"Редактирование задачи"
        #taskitem = get_object_or_404(TaskItem, id = self.kwargs['id'])
        #context['taskitem'] = taskitem
        #context['username'] = auth.get_user(self.request).username
        return context


#Delete current task
class TaskItemDeleteView(MixinUserContext, DeleteView):
    model = TaskItem

    def get_success_url(self):
        taskitem = get_object_or_404(TaskItem, id = self.kwargs['pk'])
        return reverse_lazy('tasks:task-detail', kwargs={'pk':taskitem.commontask.id})

    def delete(self, request, *args, **kwargs):
        taskitem = super (TaskItemDeleteView, self).delete(request, *args, **kwargs)
        messages.success(self.request, u'Задача {} удалена'.format(self.object.discription))
        return taskitem

tasks/templates/tasks/task_confirm_delete.html
{% extends "base.html" %}

{% load static from staticfiles %}

{% block title %}Mr. Pencil - удаление напоминалки {{ task.id }} {% endblock title %}


{% block custom_css %}
    <link href="{% static "css/form.css" %}" rel="stylesheet">
{% endblock custom_css %}



{% block main_content %}
  <h3> Напоминалка {{ task.title }} будет удалена!</h3><br>
    <!--Удаление напоминалки-->
    <form class ="custome" method="post">
      {% csrf_token %}
      <input id="custom_btn" class="btn btn-danger"  type='submit' value="Удалить">
    </form>
{% endblock main_content %}

tasks/templates/tasks/task_detail.html
{% extends "base.html" %}

{% load static from staticfiles %}

{% block title %}Mr. Pencil - задание {{ task.id }}{% endblock title %}

{% block nav_class_desktop %}{% endblock %}

{% block custom_css %}
    <link href="{% static "css/task-detail.css" %}" rel="stylesheet">
{% endblock custom_css %}

{% block main_content %}
{% include "inc_message.html" %}
    <div class="row settings">
        <div class="col-sm-12 col-md-2">
           <span class="glyphicon glyphicon-calendar" aria-hidden="true" title="Дата создания"></span>
           {{ task.time_public|date:"d m Y" }}
        </div>
        <div class="col-sm-12 col-md-2">
            {{ task.theme }}
        </div>
        <div class="col-sm-12 col-md-2">
            {% if  task.impotent %}
              <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true" title="Важное"></span>
            {% endif %}
        </div>
        <div class="col-sm-12 col-md-2">
          {% if  task.not_done == 'all done' %}
            <span  class="glyphicon glyphicon-ok" aria-hidden="true" title="Все задания выполнены!"></span>
          {% endif %}
        </div>
        <div class="col-sm-12 col-md-2">
          {% if  task.fire %}
            <span  class="glyphicon glyphicon-fire" aria-hidden="true" title="Горящая напоминалка"></span>
          {% endif %}
        </div>
        <div class="col-sm-12 col-md-2">
          <span class="glyphicon glyphicon-bell" aria-hidden="true" title="Deadline"></span>
          {{ task.time_finish|date:"d m Y" }}
        </div>
    </div>
    <div class="row">
        <h4>{{ task.title }}</h4>
    </div>
    <div class="row">
        <div class="table-responsive">
          <table ip = 'base-python' class="table table-striped">
            <tbody>
              {% for taskite in task.taskitem_set.all %}
                <tr>
                  <td>
                    {{ forloop.counter }}
                  </td>
                  <td>
                      {% if  taskite.status %}
                        <span class="glyphicon glyphicon-ok" aria-hidden="true" title="Готово"></span>
                      {% endif %}
                  </td>
                  <td>
                    <a href="{% url 'tasks:edit-item' taskite.id %}" title="Изменить">
                        {{ taskite.discription }}
                    </a>
                  </td>
                  <td>
                    <a class="del btn btn-default btn-xs " href="{% url 'tasks:delete-item' taskite.id %}" title="Удалить задачу">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                    </a>
                  </td>
                </tr>
              {% empty %}
                <p>Нет ни одной задачи.</p>
                <p>Вы можете здесь составить список из своих задач.</p>
              {% endfor %}
            </tbody>
          </table>
        </div>
    </div>
    <!--Кнопка добавить новый стикер(задачу)-->
    <div class="row">
        <div class="btn-group btn-group-custom" role="group" aria-label="...">
          <a class="btn btn-default btn-sm" href="{% url 'tasks:edit-task' task.id %}" title="Изменить напоминалку">
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          </a>
          <a class="btn btn-default btn-sm" href="{% url 'tasks:delete-task' task.id %}" title="Удалить напоминалку">
            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
          </a>
        </div>
    </div>
    <div class="row">
      <a class="add btn btn-primary btn-lg " href="{{ task.id }}/newitem/" title="Добавить задачу">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
      </a>
    </div>
{% endblock main_content %}

tasks/templates/tasks/task_form.html
{% extends "base.html" %}

{% load static from staticfiles %}

{% block title %}Mr. Pencil - {{ page_title }} {% endblock title %}


{% block custom_css %}
    <link href="{% static "css/form.css" %}" rel="stylesheet">
{% endblock custom_css %}



{% block main_content %}

  <h3> {{ page_title }} </h3><br>

    <!--Создание формы для новой задачи-->
    <form method="post" action="">
    {% csrf_token %}
    <dl class="register">
    {% for field in form %}

            <dt>{{ field.label_tag }}</dt>
            <dd class="clearfix clearfix-custom">{{ field }}
            {% if field.help_text %}<div class="clearfix clearfix-custom-help">{{ field.help_text }}</div>{% endif %}
            {% if field.errors %}<div class="myerrors clearfix clearfix-custom-errors">{{ field.errors }}</div>{% endif %}
            </dd>

    {% endfor %}
    </dl>
    <input class="custom-button" type="submit" value="сохранить" / class="clearfix">
</form>

{% endblock main_content %}

tasks/templates/tasks/task_list.html
{% extends "base.html" %}

{% load static from staticfiles %}

{% block title %}Mr. Pencil - Рабочий стол{% endblock title %}

{% block nav_class_desktop %}active{% endblock %}

{% block custom_css %}
    <link href="{% static "css/desktop.css" %}" rel="stylesheet">
{% endblock custom_css %}


{% block main_content %}
{% include "inc_message.html" %}
  <!--Фильтрация выборки студентов-->
<div class='row '>

  <div class="col-sm-12 col-md-11 common-filter">
    <div class="filter">
      <form action="" method="get">
        {% csrf_token %}
        <div class="container-filter custom-filter">
          <input type = "checkbox" name = "Impotent"  value=True /> Важные
          <select id="id_theme" name="theme">
              <option value=5>все</option>
              <option value=0>работа</option>
              <option value=1>личное</option>
              <option value=2>семья</option>
              <option value=3>покупки</option>
              <option value=4>разное</option>
          </select> Тема
          <input type = "checkbox" name = "Urgent"  value=True /> По дате выполнения
        </div>
        <div class="container-filter">
          <button type="submit" class="btn btn-primary btn-sm" aria-label="Left Align">Показать
          </button>
        </div>
      </form>

    </div>
    <div class="slidet">
      <button type="button" class="btn btn-default btn-lg" title="Фильтрация">
        <span class="glyphicon glyphicon-filter" aria-hidden="true"></span>
      </button>
    </div>
  </div>
  <div class="col-sm-12 col-md-1">
    <a class="add btn btn-success btn-md " href="{% url 'tasks:create-task' %}" title="Добавить напоминалку">
      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    </a>
  </div>
</div>
<div class="row">
  <div class="row ">
      {% for task in tasks %}
        {% if task in user.task_set.all %}
          <a href="{% url 'tasks:task-detail' task.id %}">
            <div class="thumbnail thumbnail-custom {{ task.color }}">
              <div class="caption">
                <div class="row">
                  <div class="col-sm-12 col-md-6">
                    {{ task.time_public|date:"d m Y" }}
                  </div>
                  <div class="col-sm-12 col-md-2">
                    {% if  task.fire %}
                      <span  class="glyphicon glyphicon-fire" aria-hidden="true" title="Горящая напоминалка"></span>
                    {% endif %}
                  </div>
                  <div class="col-sm-12 col-md-2">
                    {% if  task.not_done == 'all done' %}
                      <span  class="glyphicon glyphicon-ok" aria-hidden="true" title="Все задания выполнены!"></span>
                    {% endif %}
                  </div>
                  <div class="col-sm-12 col-md-2">
                    {% if  task.impotent %}
                      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true" title="Важное"></span>
                    {% endif %}
                  </div>
                </div>
                <h3>{{ task.title }}</h3>
                {% for taskitem in task.taskitem_set.all %}
                  {% if forloop.counter <= 5 %}
                    {% if  taskitem.status %}
                      <p><span class="glyphicon glyphicon-ok" aria-hidden="true" title="Готово"></span>
                    {% endif %}
                    {{ taskitem.discription }}</p>
                  {% endif %}
                {% endfor %}
                {% if task.taskitem_set.all|length > 5 %}
                  <div class="row points">
                    <p>...</p>
                  </div>
                {% endif %}
                <div class="row theme">
                  <p>{{ task.theme }}</p>
                </div>
                <div class="row">
                  <div class="col-sm-12 col-md-6">
                    {% if  task.time_finish %}
                      <span class="glyphicon glyphicon-bell" aria-hidden="true" title="Deadline"></span>
                      {{ task.time_finish|date:"d m Y" }}
                    {% endif %}
                  </div>
                  <div class="col-sm-12 col-md-6">
                    <div class="btn-group btn-group-custom" role="group" aria-label="...">
                      <a class="btn btn-default btn-xs btn-custom-js" href="{{ task.id }}/newitem/" title="Добавить задачу">
                        <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
                      </a>
                      <a class="btn btn-default btn-xs btn-custom-js" href="{% url 'tasks:edit-task' task.id %}" title="Изменить">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                      </a>
                      <a class="btn btn-default btn-xs btn-custom-js" href="{% url 'tasks:delete-task' task.id %}" title="Удалить напоминалку">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </a>
        {% endif %}
      {% endfor %}
      {% if user.task_set.all|length == 0 %}
        <div class="empty-box">
          <br><br><br><br><br><br>
          <p>Пока нет никаких напоминалок :-(</p>
        </div>
      {% endif %}
  </div>
  <!--Кнопка добавить новый стикер-->
</div>
{% endblock main_content %}

tasks/templates/tasks/taskitem_confirm_delete.html
{% extends "base.html" %}

{% load static from staticfiles %}

{% block title %}Mr. Pencil - удаление задачи {{ taskitem.id }} {% endblock title %}


{% block custom_css %}
    <link href="{% static "css/form.css" %}" rel="stylesheet">
{% endblock custom_css %}



{% block main_content %}
  <h3> Задача {{ taskitem.discription }} будет удалена!</h3><br>
    <!--Удаление напоминалки-->
    <form class ="custome" method="post">
      {% csrf_token %}
      <input id="custom_btn" class="btn btn-danger"  type='submit' value="Удалить">
    </form>
{% endblock main_content %}

tasks/templates/tasks/taskitem_form.html
{% extends "base.html" %}

{% load static from staticfiles %}

{% block title %}Mr. Pencil - {{ page_title }} {% endblock title %}


{% block custom_css %}
    <link href="{% static "css/form.css" %}" rel="stylesheet">
{% endblock custom_css %}



{% block main_content %}

  <h3> {{ page_title }} </h3><br>
  <!--Создание формы для новой задачи-->
  <form method="post" action="">
    {% csrf_token %}
    <dl class="register">
    {% for field in form %}
        <dt>{{ field.label_tag }}</dt>
        <dd class="clearfix clearfix-custom">{{ field }}
        {% if field.help_text %}<div class="clearfix clearfix-custom-help">{{ field.help_text }}</div>{% endif %}
        {% if field.errors %}<div class="myerrors clearfix clearfix-custom-errors">{{ field.errors }}</div>{% endif %}
        </dd>
    {% endfor %}
    </dl>
    <input class="custom-button" type="submit" value="сохранить" / class="clearfix">
</form>
{% endblock main_content %}