stickers/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.contrib import admin

from stickers import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.IndexView.as_view(), name = 'index'),
    #url(r'^desktop/', include('tasks.urls', namespace = "tasks")),
    url(r'^accounts/', include('registration.urls')),
    url(r'^accounts/profile/', include('tasks.urls', namespace = "tasks")),
    url(r'', include('social_auth.urls')),
]

tasks/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from tasks import views

urlpatterns = [
    url(r'^$', views.TaskListView.as_view(), name = 'tasks-list'),
    url(r'^(?P<pk>\d+)$', views.TaskDetailView.as_view(), name = 'task-detail'),
    url(r'^newtask/$', views.TaskCreateView.as_view(), name = 'create-task'),
    url(r'^deletetask/(?P<pk>\d+)$', views.TaskDeleteView.as_view(), name = 'delete-task'),
    url(r'^edittask/(?P<pk>\d+)$', views.TaskUpdateView.as_view(), name = 'edit-task'),
    url(r'^(?P<pk>\d+)/newitem/$', views.TaskItemCreateView.as_view(), name = 'create-item'),
    url(r'^edititem/(?P<pk>\d+)$', views.TaskItemUpdateView.as_view(), name = 'edit-item'),
    url(r'^deleteitem/(?P<pk>\d+)$', views.TaskItemDeleteView.as_view(), name = 'delete-item'),
    #url(r'^(?P<pk>\d+)/$', views.CourseDetailView.as_view(), name = 'course'),
    #Урлы для редактирование курса
    #url(r'^add/$', views.CourseCreateView.as_view(), name = 'create-course'),
    #url(r'^edit/(?P<pk>\d+)/$', views.CourseUpdateView.as_view(), name = 'edit-course'),
    #url(r'^remove/(?P<pk>\d+)/$', views.CourseDeleteView.as_view(), name = 'remove-course'),
    #Урлы для редактирования урока
#    url(r'^(?P<pk>\d+)/add_lesson/$', views.create_lesson, name = 'create-lesson'),
#    url(r'^(?P<pk>\d+)/edit_lesson/$', views.edit_lesson, name = 'edit-lesson'),
#    url(r'^(?P<pk>\d+)/remove_lesson/$', views.remove_lesson, name = 'remove-lesson'),
]

templates/base.html
 <!DOCTYPE html>
{% load static from staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static "images/icon.gif" %}">

    <title>{% block title %}Mr. Pencil{% endblock title %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "bootstrap/css/bootstrap.css" %}" rel="stylesheet">
    <link href="{% static "bootstrap/css/font-awesome.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "bootstrap/css/cover.css" %}" rel="stylesheet">
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <!--В этом месте подключаются стили для конкретной странички-->
    {% block custom_css %}
    {% endblock custom_css %}
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static "JS/ie-emulation-modes-warning.js" %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">
          <!--Head-->

            <div class="masthead clearfix custom">
              <div class="inner">
                <div class="row">
                  <div class="col-sm-12 col-md-2">
                    <a href="{% url 'auth_logout' %}"><img class="logo masthead-brand" src="{% static 'images/logo.gif' %}" title='Привет! Mr. Pencil - это я!'></a>
                  </div>
                  <div class="col-sm-12 col-md-4">
                    <h3>{{ username }}</h3>
                  </div>
                  <div class="col-sm-12 col-md-6">
                    <nav>
                      <ul class="nav masthead-nav">
                        {% if username %}
                          <li class="{% block nav_class_desktop %}{% endblock %}"><a href="{% url 'tasks:tasks-list' %}" title="Рабочий стол">Рабочий стол</a></li>
                        {% endif %}
                        {% if username %}
                          <li class="{% block nav_class_sign_out %}{% endblock %}"><a href="{% url 'auth_logout' %}" title="Выйти">Выйти</a></li>
                        {% else %}
                          <li class="{% block nav_class_sign_up %}{% endblock %}"><a href="{% url 'registration_register' %}" title="Зарегистрироваться">Регистрация</a></li>
                          <li class="{% block nav_class_sign_in %}{% endblock %}"><a href="{% url 'auth_login' %}" title="Войти">Войти</a></li>
                        {% endif %}
                      </ul>
                    </nav>
                  </div>
                </div>
              </div>
            </div>
          <div class="row row-wrapper">
            {% block main_content %}

            {% endblock main_content %}
          </div>
          <!--Footer-->
          <div class="mastfoot custom-footer">
            <div class="inner">
              <p>Самый тупой карандаш - острее нашей памяти. @Mr. Pencil</p>
            </div>
          </div>

        </div>

      </div>

    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="{% static "bootstrap/js/bootstrap.js"%}"></script>
    <!--My script-->
    <script src="{% static "JS/script.js"%}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static "JS/ie10-viewport-bug-workaround.js"%}"></script>
  </body>
</html>

templates/inc_message.html
{% if messages %}
  <div class="alert alert-default alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <ul class="messages">
      {% for message in messages %}
        <lo{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</lo>
      {% endfor %}
    </ul>
  </div>
{% endif %}

templates/index.html
{% extends "base.html" %}

{% load static from staticfiles %}

{% block title %}Mr. Pencil - Начало{% endblock title %}


{% block custom_css %}
    <link href="{% static "css/index.css" %}" rel="stylesheet">
{% endblock custom_css %}


{% block main_content %}
  <div class="inner cover custom-div">
    <h1 class="cover-heading">Mr. Pencil</h1>
    <p class="lead">Хочешь везде успеть?</p>
    <p class="lead">Хочешь ничего не забыть?</p>
    <p class="lead">Хочешь не рисовать крестики на руке?</p>
    <p class="lead">Дружи со мной и память тебя не подведет!</p>
    <p class="lead">
      <a href="{% url 'registration_register' %}" class="btn btn-lg btn-default" title="Зарегистрироваться">Хочу</a>
    </p>
  </div>
{% endblock main_content %}